name: Build and deploy FastAPI app to Azure Web App - tech0-gen8-step4-pos-app-98

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # Pythonのセットアップ
      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # 依存関係のインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 必要なファイルをデプロイ用ディレクトリにコピー
      - name: Copy artifacts for deployment job
        run: |
          mkdir deploy
          cp -r ./app ./deploy
          cp ./requirements.txt ./deploy
          cp .env ./deploy   # 必要なら追加

      # デプロイ用のアーティファクトをZIPに圧縮
      - name: Zip artifact for deployment
        run: zip -r release.zip ./deploy

      # アーティファクトをアップロード
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: fastapi-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: fastapi-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tech0-gen8-step4-pos-app-98'
          slot-name: 'Production'
          package: ./deploy
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B9DB7EB34575454489C00F3265DFCA9F }}
