name: Build and deploy FastAPI app to Azure Web App - tech0-gen8-step4-pos-app-98

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # Pythonのセットアップ
      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # 仮想環境の作成とアクティベート
      - name: Create and activate virtual environment
        run: |
          python3 -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # 必要なファイルをデプロイ用ディレクトリにコピー
      - name: Copy artifacts for deployment job
        run: |
          mkdir deploy
          cp -r ./app ./deploy
          cp ./requirements.txt ./deploy

      # startup.sh スクリプトを作成
      - name: Create startup.sh script
        run: |
          echo '#!/bin/bash' > ./deploy/startup.sh
          echo 'if [ ! -d "/home/site/wwwroot/antenv" ]; then' >> ./deploy/startup.sh
          echo '  python3 -m venv /home/site/wwwroot/antenv' >> ./deploy/startup.sh
          echo 'fi' >> ./deploy/startup.sh
          echo 'source /home/site/wwwroot/antenv/bin/activate' >> ./deploy/startup.sh
          echo 'pip install --upgrade pip' >> ./deploy/startup.sh
          echo 'pip install -r /home/site/wwwroot/requirements.txt' >> ./deploy/startup.sh
          echo 'uvicorn main:app --host 0.0.0.0 --port 8000' >> ./deploy/startup.sh
          chmod +x ./deploy/startup.sh

      # デプロイ用のアーティファクトをZIPに圧縮
      - name: Zip artifact for deployment
        run: zip -r release.zip ./deploy

      # アーティファクトをアップロード
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: fastapi-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: fastapi-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tech0-gen8-step4-pos-app-98'
          slot-name: 'Production'
          package: ./deploy
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B9DB7EB34575454489C00F3265DFCA9F }}
